# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [1]:
import numpy as np

In [10]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.random.rand(3, 3)
A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
B

array([[0.54992512, 0.93251432, 0.6952647 ],
       [0.32381322, 0.06091187, 0.73924847],
       [0.69885699, 0.43760496, 0.96502424]])

In [12]:
C = A + 20
C

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [13]:
print(A.dot(B+C))

[[153.29412253 158.36715294 167.06883437]
 [374.01190853 387.66024639 408.26744661]
 [594.72969453 616.95333984 649.46605885]]


In [14]:
print((A.dot(B)) + (A.dot(C)))

[[153.29412253 158.36715294 167.06883437]
 [374.01190853 387.66024639 408.26744661]
 [594.72969453 616.95333984 649.46605885]]


## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [15]:
print(A.dot(B.dot(C)))

[[ 262.8467716   273.57688144  284.30699128]
 [ 659.31705082  686.25665235  713.19625387]
 [1055.78733004 1098.93642326 1142.08551647]]


In [16]:
print((A.dot(B)).dot(C))

[[ 262.8467716   273.57688144  284.30699128]
 [ 659.31705082  686.25665235  713.19625387]
 [1055.78733004 1098.93642326 1142.08551647]]


## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [17]:
print(A.dot(B))

[[ 3.29412253  2.36715294  5.06883437]
 [ 8.01190853  6.66024639 12.26744661]
 [12.72969453 10.95333984 19.46605885]]


In [18]:
print(B.dot(A))

[[ 9.1468353  11.32453945 13.50224359]
 [ 5.74220001  6.86617357  7.99014714]
 [ 9.20444651 11.3059327  13.40741889]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [21]:
x = np.array([[6], [23], [9]])
y = np.array([[7], [5], [2]])
print(x, y)

[[ 6]
 [23]
 [ 9]] [[7]
 [5]
 [2]]


In [22]:
print((x.T).dot(y))

[[175]]


In [23]:
print((y.T).dot(x))

[[175]]


#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [24]:
print((A.dot(B)).T)

[[ 3.29412253  8.01190853 12.72969453]
 [ 2.36715294  6.66024639 10.95333984]
 [ 5.06883437 12.26744661 19.46605885]]


In [25]:
print((B.T).dot(A.T))

[[ 3.29412253  8.01190853 12.72969453]
 [ 2.36715294  6.66024639 10.95333984]
 [ 5.06883437 12.26744661 19.46605885]]


## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 